version: '3.8'
services:

  backend:
    build: ./backend
    container_name: backend
    user: "1000:1000"
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
    

  pgdb:
    image: postgres:11
    container_name: pgdb
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    volumes:
      - pgdata:/var/lib/postgresql/data/
    
volumes:
  pgdata: